listmonk:
  image: listmonk/listmonk:latest
  uploadPath: /listmonk/uploads
  storage: 10Gi
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      memory: 1Gi

postgres:
  image: postgres:16
  db: listmonk
  user: listmonk
  storage: 10Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi

ingress:
  enabled: true
  clusterIssuer: letsencrypt-prod
  private:
    className: nginx-private
    host: listmonk.rifflabs.io
  public:
    className: nginx-public
    host: lists.rifflabs.io
    paths:
      - /subscription
      - /link
      - /campaign
      - /archive
      - /api/public
      - /public
      - /uploads
      - /health

secretsBootstrap:
  secretName: listmonk-secrets
  secretStoreName: doppler-secrets-listmonk
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteKey: POSTGRES_PASSWORD
