serverName: hunterwittenborn.com

certManager:
  clusterIssuer: letsencrypt-prod

ingress:
  className: nginx-public

elementAdmin:
  ingress:
    host: admin.matrix.hunterwittenborn.com

elementWeb:
  additional:
    disable_custom_urls: "true"
  ingress:
    host: chat.matrix.hunterwittenborn.com

hookshot:
  enabled: true
  ingress:
    host: hookshot.matrix.hunterwittenborn.com
  additional:
    0-generic:
      config: |
        generic:
          enabled: true
          urlPrefix: https://hookshot.matrix.hunterwittenborn.com/webhook/
    1-permissions:
      config: |
        permissions:
          - actor: "@hunter:hunterwittenborn.com"
            services:
              - service: "*"
                level: admin

matrixAuthenticationService:
  ingress:
    host: account.matrix.hunterwittenborn.com

matrixRTC:
  ingress:
    host: call.matrix.hunterwittenborn.com

synapse:
  ingress:
    host: api.matrix.hunterwittenborn.com
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "100m"

wellKnownDelegation:
  enabled: false
