apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.rclone.configSecretName }}
  labels:
    {{- include "rclone-s3.labels" . | nindent 4 }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-cluster-store
    kind: ClusterSecretStore
  target:
    name: {{ .Values.rclone.configSecretName }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.rclone.configSecretKey }}
      remoteRef:
        key: {{ .Values.rclone.bitwardenSecretId | quote }}
