rclone:
  image: rclone/rclone:1.69.1
  remote: "gdrive:"
  address: :8080
  authSecretName: rclone-s3-auth
  credentialsSecretName: cloud-credentials
  configSecretName: rclone-config
  configSecretKey: rclone.conf
  secretStoreName: doppler-secrets-velero
  remoteKey: RCLONE_CONFIG
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 512Mi
