schedules:
  hourly:
    enabled: true
    schedule: "0 0-2,4-23 * * *"
    ttl: 12h0m0s
  daily:
    enabled: true
    schedule: "0 3 * * 0-5"
    ttl: 168h0m0s
  weekly:
    enabled: true
    schedule: "0 3 * * 6"
    ttl: 2016h0m0s
