{{- range $name, $schedule := .Values.schedules }}
{{- if $schedule.enabled }}
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: {{ $name }}
spec:
  schedule: {{ $schedule.schedule | quote }}
  template:
    includedNamespaces:
      - '*'
    includeClusterResources: true
    storageLocation: default
    defaultVolumesToFsBackup: true
    ttl: {{ $schedule.ttl | quote }}
---
{{- end }}
{{- end }}
