n8n:
  image: docker.n8n.io/n8nio/n8n:latest
  timezone: America/Chicago
  storage: 5Gi
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      memory: 2Gi

postgres:
  image: postgres:16
  db: n8n
  user: n8n
  schema: public
  storage: 10Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      memory: 512Mi

ingress:
  enabled: true
  className: traefik
  host: n8n.hunterwittenborn.com
  clusterIssuer: letsencrypt-prod

secretsBootstrap:
  secretName: n8n-secrets
  secretStoreName: doppler-secrets-n8n
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteKey: POSTGRES_PASSWORD
    - secretKey: N8N_ENCRYPTION_KEY
      remoteKey: N8N_ENCRYPTION_KEY
