---
- name: Ensure external-secrets namespace exists
  kubernetes.core.k8s:
    state: present
    api_version: v1
    kind: Namespace
    name: external-secrets

- name: Create or update Doppler token secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: doppler-token
        namespace: external-secrets
      type: Opaque
      stringData:
        dopplerToken: "{{ doppler_token }}"
