litellm:
  image: docker.litellm.ai/berriai/litellm:main-stable
  storeModelInDb: "True"
  docsUrl: "/docs"
  rootRedirectUrl: "/ui"
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      memory: 2Gi

postgres:
  image: postgres:16
  db: litellm
  user: litellm
  storage: 5Gi
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 256Mi

ingress:
  enabled: true
  className: traefik
  host: litellm.hunterwittenborn.com
  clusterIssuer: letsencrypt-prod

sso:
  enabled: true
  authEndpoint: "https://clerk.hunterwittenborn.com/oauth/authorize"
  tokenEndpoint: "https://clerk.hunterwittenborn.com/oauth/token"
  userInfoEndpoint: "https://clerk.hunterwittenborn.com/oauth/userinfo"
  scope: "openid profile email"
  userIdAttribute: "sub"
  userEmailAttribute: "email"
  adminId: "user_3AJzTWpt47JGfsAFiKnEi8MNmNI"
  autoRedirectToSSO: true

secretsBootstrap:
  secretName: litellm-secrets
  secretStoreName: doppler-secrets-litellm
  data:
    - secretKey: LITELLM_MASTER_KEY
      remoteKey: LITELLM_MASTER_KEY
    - secretKey: POSTGRES_PASSWORD
      remoteKey: POSTGRES_PASSWORD
    - secretKey: OIDC_CLIENT_ID
      remoteKey: OIDC_CLIENT_ID
    - secretKey: OIDC_CLIENT_SECRET
      remoteKey: OIDC_CLIENT_SECRET
    - secretKey: OIDC_CLIENT_STATE
      remoteKey: OIDC_CLIENT_STATE
