apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/hwittenborn/homelab.git
        revision: main
        files:
          - path: "k8s/apps/**/config.json"
  template:
    metadata:
      name: "{{ .name }}"
      annotations:
        argocd.argoproj.io/sync-wave: "{{ .syncWave }}"
    spec:
      project: default
      source:
        repoURL: https://github.com/hwittenborn/homelab.git
        targetRevision: main
        path: "{{ .path.path }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .namespace }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
