credentials:
  useSecret: true
  existingSecret: cloud-credentials

initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.13.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

configuration:
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: velero
      default: true
      config:
        region: minio
        s3Url: http://rclone-s3.velero.svc.cluster.local:8080
        s3ForcePathStyle: "true"

deployNodeAgent: true
snapshotsEnabled: false
defaultVolumesToFsBackup: true
