credentials:
  useSecret: true
  existingSecret: cloud-credentials

initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.13.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

configuration:
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: hwittenborn-homelab
      default: true
      config:
        region: us-east-1
        s3Url: https://s3.wasabisys.com
        s3ForcePathStyle: "true"
  volumeSnapshotLocation: []

deployNodeAgent: true
snapshotsEnabled: false
defaultVolumesToFsBackup: true

extraObjects:
  - apiVersion: external-secrets.io/v1
    kind: ExternalSecret
    metadata:
      name: cloud-credentials
      namespace: velero
    spec:
      refreshInterval: "1h"
      secretStoreRef:
        name: doppler-secrets-velero
        kind: ClusterSecretStore
      target:
        name: cloud-credentials
        creationPolicy: Owner
        template:
          engineVersion: v2
          data:
            cloud: |
              [default]
              aws_access_key_id={{ `{{ .S3_ACCESS_KEY }}` }}
              aws_secret_access_key={{ `{{ .S3_SECRET_KEY }}` }}
      data:
        - secretKey: S3_ACCESS_KEY
          remoteRef:
            key: "S3_ACCESS_KEY"
        - secretKey: S3_SECRET_KEY
          remoteRef:
            key: "S3_SECRET_KEY"
  - apiVersion: external-secrets.io/v1
    kind: ExternalSecret
    metadata:
      name: velero-repo-credentials
      namespace: velero
    spec:
      refreshInterval: "1h"
      secretStoreRef:
        name: doppler-secrets-velero
        kind: ClusterSecretStore
      target:
        name: velero-repo-credentials
        creationPolicy: Owner
        template:
          engineVersion: v2
          data:
            repository-password: "{{ `{{ .VELERO_REPOSITORY_PASSWORD }}` }}"
      data:
        - secretKey: VELERO_REPOSITORY_PASSWORD
          remoteRef:
            key: "VELERO_REPOSITORY_PASSWORD"
  - apiVersion: velero.io/v1
    kind: Schedule
    metadata:
      name: hourly
      namespace: velero
    spec:
      schedule: "0 0-2,4-23 * * *"
      template:
        includedNamespaces:
          - '*'
        includeClusterResources: true
        storageLocation: default
        defaultVolumesToFsBackup: true
        ttl: 12h0m0s
  - apiVersion: velero.io/v1
    kind: Schedule
    metadata:
      name: daily
      namespace: velero
    spec:
      schedule: "0 3 * * 0-5"
      template:
        includedNamespaces:
          - '*'
        includeClusterResources: true
        storageLocation: default
        defaultVolumesToFsBackup: true
        ttl: 168h0m0s
  - apiVersion: velero.io/v1
    kind: Schedule
    metadata:
      name: weekly
      namespace: velero
    spec:
      schedule: "0 3 * * 6"
      template:
        includedNamespaces:
          - '*'
        includeClusterResources: true
        storageLocation: default
        defaultVolumesToFsBackup: true
        ttl: 2016h0m0s
