apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-secrets
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-cluster-store
    kind: ClusterSecretStore
  target:
    name: {{include "litellm.secretName" .}}
    creationPolicy: Owner
  data:
    - secretKey: LITELLM_MASTER_KEY
      remoteRef:
        key: {{.Values.litellm.masterKeySecretId | quote}}
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: {{.Values.postgres.passwordSecretId | quote}}
{{- if .Values.sso.enabled }}
    - secretKey: GENERIC_CLIENT_ID
      remoteRef:
        key: {{ .Values.sso.clientIdSecretId | quote }}
    - secretKey: GENERIC_CLIENT_SECRET
      remoteRef:
        key: {{ .Values.sso.clientSecretSecretId | quote }}
    - secretKey: GENERIC_CLIENT_STATE
      remoteRef:
        key: {{ .Values.sso.clientStateSecretId | quote }}
{{- end }}
