apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: litellm
  template:
    metadata:
      labels:
        app: litellm
    spec:
      containers:
        - name: litellm
          image: {{.Values.litellm.image}}
          ports:
            - name: http
              containerPort: 4000
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{include "litellm.secretName" .}}
                  key: POSTGRES_PASSWORD
            - name: DATABASE_URL
              value: "postgresql://{{ .Values.postgres.user }}:$(POSTGRES_PASSWORD)@postgres:5432/{{ .Values.postgres.db }}"
            - name: STORE_MODEL_IN_DB
              value: {{.Values.litellm.storeModelInDb | quote}}
            - name: LITELLM_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{include "litellm.secretName" .}}
                  key: LITELLM_MASTER_KEY
          livenessProbe:
            httpGet:
              path: /health/liveliness
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 4000
            initialDelaySeconds: 40
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources: {{- toYaml .Values.litellm.resources | nindent 12}}
---
apiVersion: v1
kind: Service
metadata:
  name: litellm
spec:
  type: ClusterIP
  selector:
    app: litellm
  ports:
    - name: http
      port: 4000
      targetPort: http
