apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: litellm
  template:
    metadata:
      labels:
        app: litellm
    spec:
      containers:
        - name: litellm
          image: {{.Values.litellm.image}}
          ports:
            - name: http
              containerPort: 4000
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{include "litellm.secretName" .}}
                  key: POSTGRES_PASSWORD
            - name: DATABASE_URL
              value: "postgresql://{{ .Values.postgres.user }}:$(POSTGRES_PASSWORD)@postgres:5432/{{ .Values.postgres.db }}"
            - name: STORE_MODEL_IN_DB
              value: {{.Values.litellm.storeModelInDb | quote}}
            - name: LITELLM_DROP_PARAMS
              value: "True"
            - name: LITELLM_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{include "litellm.secretName" .}}
                  key: LITELLM_MASTER_KEY
{{- if .Values.litellm.docsUrl }}
            - name: DOCS_URL
              value: {{ .Values.litellm.docsUrl | quote }}
{{- end }}
{{- if .Values.litellm.rootRedirectUrl }}
            - name: ROOT_REDIRECT_URL
              value: {{ .Values.litellm.rootRedirectUrl | quote }}
{{- end }}
{{- if .Values.sso.enabled }}
            - name: GENERIC_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "litellm.secretName" . }}
                  key: GENERIC_CLIENT_ID
            - name: GENERIC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "litellm.secretName" . }}
                  key: GENERIC_CLIENT_SECRET
            - name: GENERIC_AUTHORIZATION_ENDPOINT
              value: {{ .Values.sso.authEndpoint | quote }}
            - name: GENERIC_TOKEN_ENDPOINT
              value: {{ .Values.sso.tokenEndpoint | quote }}
            - name: GENERIC_USERINFO_ENDPOINT
              value: {{ .Values.sso.userInfoEndpoint | quote }}
            - name: GENERIC_SCOPE
              value: {{ .Values.sso.scope | quote }}
            - name: GENERIC_CLIENT_STATE
              valueFrom:
                secretKeyRef:
                  name: {{ include "litellm.secretName" . }}
                  key: GENERIC_CLIENT_STATE
            - name: PROXY_BASE_URL
              value: "https://{{ .Values.ingress.host }}"
            - name: GENERIC_USER_ID_ATTRIBUTE
              value: {{ .Values.sso.userIdAttribute | quote }}
            - name: GENERIC_USER_EMAIL_ATTRIBUTE
              value: {{ .Values.sso.userEmailAttribute | quote }}
{{- if .Values.sso.adminId }}
            - name: PROXY_ADMIN_ID
              value: {{ .Values.sso.adminId | quote }}
{{- end }}
{{- if .Values.sso.autoRedirectToSSO }}
            - name: AUTO_REDIRECT_UI_LOGIN_TO_SSO
              value: {{ .Values.sso.autoRedirectToSSO | quote }}
{{- end }}
{{- end }}
          livenessProbe:
            httpGet:
              path: /health/liveliness
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 4000
            initialDelaySeconds: 40
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources: {{- toYaml .Values.litellm.resources | nindent 12}}
---
apiVersion: v1
kind: Service
metadata:
  name: litellm
spec:
  type: ClusterIP
  selector:
    app: litellm
  ports:
    - name: http
      port: 4000
      targetPort: http
