apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sparky-fitness-secrets
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: bitwarden-cluster-store
    kind: ClusterSecretStore
  target:
    name: {{include "sparky-fitness.secretName" .}}
    creationPolicy: Owner
  data:
    - secretKey: SPARKY_FITNESS_DB_PASSWORD
      remoteRef:
        key: {{.Values.secrets.dbPasswordSecretId | quote}}
    - secretKey: SPARKY_FITNESS_APP_DB_PASSWORD
      remoteRef:
        key: {{.Values.secrets.appDbPasswordSecretId | quote}}
    - secretKey: SPARKY_FITNESS_API_ENCRYPTION_KEY
      remoteRef:
        key: {{.Values.secrets.apiEncryptionKeySecretId | quote}}
    - secretKey: BETTER_AUTH_SECRET
      remoteRef:
        key: {{.Values.secrets.betterAuthSecretSecretId | quote}}
