apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparkyfitness-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sparkyfitness-frontend
  template:
    metadata:
      labels:
        app: sparkyfitness-frontend
    spec:
      containers:
        - name: frontend
          image: {{.Values.frontend.image}}
          ports:
            - name: http
              containerPort: 80
          env:
            - name: SPARKY_FITNESS_FRONTEND_URL
              value: "https://{{.Values.ingress.host}}"
            - name: SPARKY_FITNESS_SERVER_HOST
              value: sparkyfitness-server
            - name: SPARKY_FITNESS_SERVER_PORT
              value: "3010"
---
apiVersion: v1
kind: Service
metadata:
  name: sparkyfitness-frontend
spec:
  type: ClusterIP
  selector:
    app: sparkyfitness-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
