apiVersion: apps/v1
kind: Deployment
metadata:
  name: rclone-s3-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rclone-s3-gateway
  template:
    metadata:
      labels:
        app: rclone-s3-gateway
    spec:
      containers:
        - name: rclone
          image: {{.Values.rcloneGateway.image}}
          args:
            - serve
            - s3
            - {{.Values.rcloneGateway.driveRemotePath | quote}}
            - --addr
            - 0.0.0.0:8080
            - --vfs-cache-mode
            - writes
          ports:
            - name: s3
              containerPort: 8080
          volumeMounts:
            - name: rclone-config
              mountPath: /config/rclone
              readOnly: true
          resources: {{- toYaml .Values.rcloneGateway.resources | nindent 12}}
      volumes:
        - name: rclone-config
          secret:
            secretName: rclone-config
---
apiVersion: v1
kind: Service
metadata:
  name: rclone-s3-service
spec:
  type: ClusterIP
  selector:
    app: rclone-s3-gateway
  ports:
    - name: s3
      port: 8080
      targetPort: s3
