upgradeCRDs: true

kubectl:
  image:
    repository: docker.io/bitnamilegacy/kubectl
    tag: "latest"

initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.13.1
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

deployNodeAgent: true

credentials:
  useSecret: true
  existingSecret: velero-s3-credentials

configuration:
  defaultVolumesToFsBackup: true
  backupStorageLocation:
    - name: default
      provider: aws
      bucket: k3s-backups
      config:
        region: minio
        s3ForcePathStyle: "true"
        s3Url: http://rclone-s3-service.velero.svc.cluster.local:8080
  volumeSnapshotLocation: []

schedules:
  hourly:
    schedule: "0 * * * *"
    template:
      ttl: "12h0m0s"
      defaultVolumesToFsBackup: true
  daily:
    schedule: "0 0 * * *"
    template:
      ttl: "336h0m0s"
      defaultVolumesToFsBackup: true
  weekly:
    schedule: "0 0 * * 0"
    template:
      ttl: "2016h0m0s"
      defaultVolumesToFsBackup: true
