ingress:
  className: traefik
  clusterIssuer: letsencrypt-prod
  host: matrix.hunterwittenborn.com

redirect:
  regex: ^https?://matrix\.hunterwittenborn\.com/?(.*)
  replacement: https://chat.matrix.hunterwittenborn.com/$1
  permanent: true

backend:
  serviceName: matrix-element-web
  servicePortName: web
