provider:
  name: cloudflare

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: api-token

sources:
  - ingress

domainFilters:
  - hunterwittenborn.com
  - koca.dev

policy: sync

txtOwnerId: hwittenborn-homelab
txtPrefix: _externaldns.
